### ISSUE TITLE
Actually used?

### ISSUE THREAD

**Issue by gforcada** [plone/plone.app.bbb_testing#1]
@gotcha I see that you are the only contributor of this package and you also created an empty plone.bbb_testing which, at least on github, is completely empty.

Do we want to keep this packages around? Is the plone.app.testing bbb layer enough already? @tisto any idea on this?

**Comment by tisto** [comment]
If @gotcha does not object I'd remove the package.

**Comment by gotcha** [comment]
For information, those were created when we wanted to add bbb code to plone.testing and plone.app.testing.
At that time, we were told to put our code outside plone.testing and p.a.testing.

This lead to another team recreating our work as they had no idea that we had started the work.

Another example of stop energy when perfection discourages people to contribute

**Comment by gotcha** [comment]
iow, yes, this can be removed
